FROM docker.io/bitnami/spark:3.5.0

ENV SPARK_RPC_AUTHENTICATION_ENABLED=no
ENV SPARK_RPC_ENCRYPTION_ENABLED=no
ENV SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
ENV SPARK_SSL_ENABLED=no
ENV SPARK_USER=spark
ENV PYSPARK_PYTHON=/opt/bitnami/python/bin/python

RUN pip install findspark

ENTRYPOINT ["/opt/bitnami/scripts/spark/entrypoint.sh"]
