x-common-args:
  &common-args
    USER_NAME: ${USER_NAME}
    USER_HOME: ${USER_HOME}

services:
  spark-master:
    build:
      context: .
      args:
        <<: *common-args
    image: dev-spark-jupyter-pyspark:3.5.1
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
    user: ${USER_NAME}
    command: /bin/bash -c "/opt/spark-3.5.1-bin-hadoop3/sbin/start-master.sh && tail -f /opt/spark-3.5.1-bin-hadoop3/logs/*"
    networks:
      - spark-network

  spark-worker:
    build:
      context: .
      args:
        <<: *common-args
    image: dev-spark-jupyter-pyspark:3.5.1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8081:8081"
    user: ${USER_NAME}
    command: /bin/bash -c "/opt/spark-3.5.1-bin-hadoop3/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark-3.5.1-bin-hadoop3/logs/*"
    depends_on:
      - spark-master
    networks:
      - spark-network

  history-server:
    build:
      context: .
      args:
        <<: *common-args
    image: dev-spark-jupyter-pyspark:3.5.1
    environment:
      - SPARK_MODE=history-server
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=${USER_HOME}/logs
      - SPARK_HISTORY_FS_UPDATE_INTERVAL=10s
    ports:
      - "18080:18080"
    volumes:
      - ./logs:${USER_HOME}/logs
    command: /bin/bash -c "/opt/spark-3.5.1-bin-hadoop3/sbin/start-history-server.sh && tail -f ${USER_HOME}/logs/*"
    depends_on:
      - spark-master
    networks:
      - spark-network


  jupyter-notebook:
    build:
      context: .
      args:
        <<: *common-args
    image: dev-spark-jupyter-pyspark:3.5.1
    # environment:
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:${USER_HOME}/notebooks
      - ./logs:${USER_HOME}/logs
    working_dir: ${USER_HOME}/notebooks
    user: ${USER_NAME}
    command: ["jupyter-lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
