services:
  jupyter:
    build:
      context: .
      dockerfile: dockerfile-jupyter
    image: jupyter/pyspark-notebook:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./logs:/home/jovyan/work/logs
    networks:
      - spark-net
    depends_on:
      - spark
networks:
  spark-net:
    driver: bridge
