FROM docker.io/jupyter/pyspark-notebook:spark-3.5.0

RUN pip install findspark

ENV PYSPARK_PYTHON=/opt/bitnami/python/bin/python

CMD ["jupyter-notebook", "--NotebookApp.token=''", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/home/jovyan/work"]
