services:
  jupyter-notebook:
    build:
      context: .
    image: dev-spark-jupyter-pyspark:3.5.1
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./logs:/logs
    working_dir: /notebooks
    command: ["jupyter-lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    networks:
      - spark-network

  spark-master:
    build:
      context: .
    image: dev-spark-jupyter-pyspark:3.5.1
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /bin/bash -c "/opt/spark-3.5.1-bin-hadoop3/sbin/start-master.sh && tail -f /opt/spark-3.5.1-bin-hadoop3/logs/*"
    networks:
      - spark-network

  spark-worker:
    build:
      context: .
    image: dev-spark-jupyter-pyspark:3.5.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    command: /bin/bash -c "/opt/spark-3.5.1-bin-hadoop3/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark-3.5.1-bin-hadoop3/logs/*"
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
